name: mlb
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - pyarrow=4.0.0
  - python=3.8.8
  - pip=21.0.1
  - cudatoolkit=10.2
  - pytorch=1.8.1
  - matplotlib
  - pandas=1.2.4
  - numpy
  - scikit-learn
  - joblib
  - tqdm=4.60.0
  - jsonnet=0.17.0
  - seaborn
  - statsmodels
  - lightgbm
  - xgboost
  - pip:
    - click
    - coloredlogs
    - omegaconf==2.0.5
    - python-dotenv
